name: .NET CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test PokemonWebAPI.Tests/PokemonWebAPI.Tests.csproj --verbosity normal
